# 関数の入出力

## 関数にスカラー，ベクトル，行列の何を入力して，何を受け取るのか意識する．

### まず，入力xをa倍して返す関数funcを作成する．

In [38]:
import numpy as np

def func(a, x):
    y = a*x
    return y

### 次に関数に2つ入力し，何が返るか確認する

### 1. スカラーとスカラーを入力して，スカラーを出力

In [39]:
a = 2
x = 4
y = func(a, x)
print(y)

8


### 2. ベクトルとスカラーを入力して，ベクトルを出力．

In [40]:
a = 3
x = np.array([1,2,3])
y = func(a, x)
print(y)

[3 6 9]


### 3. 行列とスカラー入力して，行列を出力

In [41]:
a = 3
x = np.array([[1,2,3], [4,5,6]])
y = func(a, x)
print(y)

[[ 3  6  9]
 [12 15 18]]


### numpyでベクトルを作らないとうまくいかない．

In [42]:
a = 3
x = [[1,2,3], [4,5,6]]
y = func(a, x)
print(y)

[[1, 2, 3], [4, 5, 6], [1, 2, 3], [4, 5, 6], [1, 2, 3], [4, 5, 6]]


### 4. ベクトルとベクトルを入力したら，内積になって欲しい．けど，そうはなりません．[1x4 2x5 3x6]になる

In [43]:
a = np.array([1,2,3])
b = np.array([4,5,6])
y = func(a, b)
print(y)

[ 4 10 18]


### 内積の計算はnp.dot()を使う．

In [44]:
a = np.array([1,2,3])
b = np.array([4,5,6])
y = np.dot(a, b)
print(y)

32


### 5. 行列とベクトルを入力したら，ベクトルになって欲しい．けど，そうなりません．

In [45]:
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
x = np.array([1,2,3])
y = func(A, x)
print(y)

[[ 1  4  9]
 [ 4 10 18]
 [ 7 16 27]]


### 行列・ベクトルの演算はnp.dot()を使う．

In [46]:
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
x = np.array([1,2,3])
y = np.dot(A,x)
print(y)

[14 32 50]


### ただし，xベクトルを次のように与えなければいけない．

In [47]:
x = np.array([[1],[2],[3]])
print(x)

[[1]
 [2]
 [3]]


In [52]:
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
x = np.array([[1],[2],[3]])
y = np.dot(A,x)
print(y)

[[14]
 [32]
 [50]]


### 行列演算と同じで，左から掛けるか，右から掛けるか考える必要がある．

In [53]:
y = np.dot(x,A)
print(y)

ValueError: shapes (3,1) and (3,3) not aligned: 1 (dim 1) != 3 (dim 0)

### ベクトルを与えるときは，1行3列の行列として与えてから転置して，3行1列の「ベクトル」と考えると良い．[]の入力が減って楽になる．というか，ベクトルという概念がなくて，ベクトルは行列の特殊な形という扱いである．

In [54]:
x = np.array([[1, 2, 3]])
print(x.T)

[[1]
 [2]
 [3]]
